### ISSUE TITLE
Код ревью

### ISSUE THREAD

**Issue by BaH3eP** [Egor-Ruban/Calculator#3]
1. Куча разных переменных для операции. Лучше это все объединить в один enum class

2. `Regex("([0-9]|[.])+"))` нужно вынести в отдельную переменную за for (я бы даже его вынес за функцию, т.к. у тебя еще в одной функции используется), чтобы постоянно не создавать

3. `when (word) "" -> {continue;}` Оставлять пустые скобки не очень хорошо

4. `OPERATION_NEG, BRACKET_LEFT -> operationStack.add(word)` Тут можно писать через запятую

5.  То, что происходит при "BRACKET_RIGHT" и "else" лучше вынести в отдельные функции приватные, иначе трудно читать это, а блок кода выглядит как раз под отдельную функцию

6. Если ты хочешь сделать лаконичную запись when в addToInput методе, то передавай реальный чар, а в when напиши `char in '0'..'9', char == '.' ->` и дальше то, что у тебя было написано

7. Если уж ты решил разделять логику и вью, то делай это до конца. То что у тебя в activity классе появилась Regex, которая должна быть только в объекте calculate, означает что у тебя лишняя логика вылезла там, где не нужно. Если хочешь прям шикануть, то предлагаю тебе сделать отдельный класс валидатор, который уже будет валидировать данные и в успешном случае выполнять нужное тебе действие

P.s. ставлю люкантропа за обратную польскую запись

**Comment by Egor-Ruban** [comment]
`Operations.BRACKET_RIGHT.symbol -> {
                        var operation = operationStack.last()
                        while (operation != Operations.BRACKET_LEFT.symbol) {
                            equationInRPN.add(operation)
                            operationStack.removeAt(operationStack.lastIndex)
                            operation = operationStack.last()
                        }
                        operationStack.removeAt(operationStack.lastIndex)
                    }`
Используются два листа, как это вынести в отдельную функцию? Передавать копии туда-сюда, или есть вариант поприличнее?
